### District-wise IPC Crime Analysis in India (2001–2012)

## Notebook 1 : Data Loading & Data Understanding

### Project Overview
    Crime analysis plays a crucial role in helping government agencies and law enforcement authorities identify crime patterns, allocate resources efficiently, and formulate public safety strategies.

    This project analyzes district-wise IPC crime data across India from 2001 to 2012. The analysis aims to uncover crime trends, identify high-crime regions, and generate actionable business insights using Python, SQL, and Power BI.

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

In [27]:
df1 = pd.read_csv("District_wise_crimes_committed_IPC_2001_2012.csv")

In [28]:
df=df1.copy()

In [29]:
df.head()

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,46,30,16,9,0,41,198,199,22,177,78,16,104,1,30,1131,16,149,34,175,0,181,1518,4154
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,53,30,23,8,0,16,191,366,57,309,168,11,65,8,69,1543,7,118,24,154,0,270,754,4125
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,59,34,25,4,0,14,237,723,164,559,156,33,209,9,38,2088,14,112,83,186,0,404,1262,5818
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,25,20,5,1,0,4,98,173,36,137,164,12,37,2,23,795,17,126,38,57,0,233,1181,3140
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,49,26,23,4,0,25,437,1021,150,871,70,50,220,3,41,1244,12,109,58,247,0,431,2313,6507

In [30]:
df.tail()

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
9012,LAKSHADWEEP,LAKSHADWEEP,2012,0,0,0,0,0,0,0,0,0,0,0,0,3,7,1,6,10,0,0,0,3,3,0,1,0,1,0,0,32,60
9013,LAKSHADWEEP,TOTAL,2012,0,0,0,0,0,0,0,0,0,0,0,0,3,7,1,6,10,0,0,0,3,3,0,1,0,1,0,0,32,60
9014,PUDUCHERRY,KARAIKAL,2012,5,6,2,6,0,6,2,2,0,0,1,3,21,81,53,28,17,1,15,1,1,186,0,2,0,1,0,44,392,787
9015,PUDUCHERRY,PUDUCHERRY,2012,24,21,10,7,0,7,17,14,3,5,14,13,56,577,409,168,109,8,75,5,20,632,0,7,2,5,0,219,1668,3494
9016,PUDUCHERRY,TOTAL,2012,29,27,12,13,0,13,19,16,3,5,15,16,77,658,462,196,126,9,90,6,21,818,0,9,2,6,0,263,2060,4281

In [7]:
df.sample(10)

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
3105,HIMACHAL PRADESH,TOTAL,2005,110,79,22,141,0,141,118,102,16,6,0,22,696,696,166,530,558,82,163,6,97,1359,2,286,29,228,0,480,7165,12345
7094,MIZORAM,LAWNGTLAI,2010,7,1,0,6,0,6,1,0,1,0,0,3,23,45,0,45,0,3,13,1,0,3,0,2,0,0,0,12,36,156
2364,HIMACHAL PRADESH,KULLU,2004,9,4,0,13,0,13,13,11,2,0,0,7,50,40,8,32,40,4,9,0,6,56,1,11,1,10,0,47,469,790
3787,GUJARAT,NARMADA,2006,11,8,0,2,0,2,6,6,0,2,0,1,25,30,10,20,10,4,3,1,4,100,0,6,0,10,0,47,373,643
2609,NAGALAND,TOTAL,2004,70,33,5,18,0,18,23,4,19,14,0,117,70,255,26,229,6,11,28,0,5,52,0,3,1,0,0,34,239,984
3552,UTTAR PRADESH,SONBHADRA,2005,24,17,19,8,0,8,7,5,2,1,0,5,29,57,17,40,10,16,32,5,6,60,10,6,20,11,0,95,81,519
522,RAJASTHAN,PALI,2001,43,53,2,25,0,25,77,61,16,0,0,14,193,294,70,224,138,66,185,2,36,53,15,115,2,196,0,132,2999,4640
6297,MANIPUR,BISHNUPUR,2009,16,35,0,2,0,2,7,5,2,0,16,0,5,20,8,12,3,0,9,0,12,30,0,10,0,0,0,0,103,268
3697,ASSAM,SIBSAGAR,2006,77,30,3,54,0,54,79,79,0,2,0,24,94,378,37,341,67,12,42,2,26,234,3,65,0,133,0,80,573,1978
8043,TAMIL NADU,TRICHY RLY.,2011,5,1,0,0,0,0,0,0,0,0,0,3,1,104,1,103,1,0,0,0,0,10,0,3,1,1,0,6,94,230

In [8]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 9017
Columns : 33

### Observation
    The dataset contains 9017 rows and 33 columns.

    Each row represents crime statistics for a specific district and year.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9017 entries, 0 to 9016
Data columns (total 33 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   STATE/UT                                             9017 non-null   object
 1   DISTRICT                                             9017 non-null   object
 2   YEAR                                                 9017 non-null   int64
 3   MURDER                                               9017 non-null   int64
 4   ATTEMPT TO MURDER                                    9017 non-null   int64
 5   CULPABLE HOMICIDE NOT AMOUNTING TO MURDER            9017 non-null   int64
 6   RAPE                                                 9017 non-null   int64
 7   CUSTODIAL RAPE                                       9017 non-null   int64
 8   OTHER RAPE                                           9017 non-null   int64
 9   KIDNAPPING & ABDUCTION                               9017 non-null   int64
 10  KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS          9017 non-null   int64
 11  KIDNAPPING AND ABDUCTION OF OTHERS                   9017 non-null   int64
 12  DACOITY                                              9017 non-null   int64
 13  PREPARATION AND ASSEMBLY FOR DACOITY                 9017 non-null   int64
 14  ROBBERY                                              9017 non-null   int64
 15  BURGLARY                                             9017 non-null   int64
 16  THEFT                                                9017 non-null   int64
 17  AUTO THEFT                                           9017 non-null   int64
 18  OTHER THEFT                                          9017 non-null   int64
 19  RIOTS                                                9017 non-null   int64
 20  CRIMINAL BREACH OF TRUST                             9017 non-null   int64
 21  CHEATING                                             9017 non-null   int64
 22  COUNTERFIETING                                       9017 non-null   int64
 23  ARSON                                                9017 non-null   int64
 24  HURT/GREVIOUS HURT                                   9017 non-null   int64
 25  DOWRY DEATHS                                         9017 non-null   int64
 26  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  9017 non-null   int64
 27  INSULT TO MODESTY OF WOMEN                           9017 non-null   int64
 28  CRUELTY BY HUSBAND OR HIS RELATIVES                  9017 non-null   int64
 29  IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES          9017 non-null   int64
 30  CAUSING DEATH BY NEGLIGENCE                          9017 non-null   int64
 31  OTHER IPC CRIMES                                     9017 non-null   int64
 32  TOTAL IPC CRIMES                                     9017 non-null   int64
dtypes: int64(31), object(2)
memory usage: 2.3+ MB

In [10]:
df.columns.tolist()

['STATE/UT',
 'DISTRICT',
 'YEAR',
 'MURDER',
 'ATTEMPT TO MURDER',
 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',
 'RAPE',
 'CUSTODIAL RAPE',
 'OTHER RAPE',
 'KIDNAPPING & ABDUCTION',
 'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
 'KIDNAPPING AND ABDUCTION OF OTHERS',
 'DACOITY',
 'PREPARATION AND ASSEMBLY FOR DACOITY',
 'ROBBERY',
 'BURGLARY',
 'THEFT',
 'AUTO THEFT',
 'OTHER THEFT',
 'RIOTS',
 'CRIMINAL BREACH OF TRUST',
 'CHEATING',
 'COUNTERFIETING',
 'ARSON',
 'HURT/GREVIOUS HURT',
 'DOWRY DEATHS',
 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
 'INSULT TO MODESTY OF WOMEN',
 'CRUELTY BY HUSBAND OR HIS RELATIVES',
 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
 'CAUSING DEATH BY NEGLIGENCE',
 'OTHER IPC CRIMES',
 'TOTAL IPC CRIMES']

In [11]:
df.describe()

,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
count,9017.000000,9017.00000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000
mean,2006.629034,89.28535,78.069646,9.895531,53.041366,0.005767,53.035599,79.152046,58.535433,20.616613,13.177110,7.084618,55.066430,247.829433,776.428968,281.772208,494.656759,171.881335,40.816458,170.255517,5.926140,25.219918,747.893091,20.228901,100.511257,27.515582,194.122435,0.197849,222.216702,2174.299434,5310.115116
std,3.463623,327.27503,303.446020,59.521657,190.741450,0.115223,190.725474,317.630964,246.937464,88.586415,56.778798,42.350314,220.576876,941.233426,2935.008640,1164.677928,1895.366707,685.061783,172.042434,743.536365,25.985903,98.880282,3024.106467,96.970466,394.059436,167.237522,831.986594,2.415039,936.002540,7988.438462,18524.381119
min,2001.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2004.000000,18.00000,10.000000,0.000000,8.000000,0.000000,8.000000,10.000000,6.000000,1.000000,1.000000,0.000000,6.000000,31.000000,88.000000,12.000000,64.000000,11.000000,4.000000,13.000000,0.000000,2.000000,43.000000,1.000000,10.000000,0.000000,11.000000,0.000000,5.000000,265.000000,853.000000
50%,2007.000000,38.00000,28.000000,2.000000,20.000000,0.000000,20.000000,25.000000,18.000000,5.000000,3.000000,0.000000,17.000000,83.000000,217.000000,48.000000,152.000000,46.000000,11.000000,37.000000,1.000000,8.000000,199.000000,5.000000,31.000000,2.000000,47.000000,0.000000,68.000000,745.000000,2096.000000
75%,2010.000000,66.00000,56.000000,6.000000,41.000000,0.000000,41.000000,56.000000,42.000000,13.000000,9.000000,2.000000,37.000000,177.000000,466.000000,140.000000,313.000000,125.000000,28.000000,104.000000,4.000000,20.000000,529.000000,16.000000,76.000000,13.000000,135.000000,0.000000,177.000000,1608.000000,3972.000000
max,2012.000000,7601.00000,7964.000000,1616.000000,3425.000000,5.000000,3425.000000,8878.000000,7910.000000,2416.000000,1319.000000,1263.000000,6949.000000,16617.000000,53449.000000,22773.000000,35960.000000,11214.000000,4296.000000,19646.000000,599.000000,2830.000000,56768.000000,2322.000000,7118.000000,4970.000000,19865.000000,83.000000,16076.000000,124176.000000,220335.000000

In [12]:
df.describe(include='all')

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
count,9017,9017,9017.000000,9017.00000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000,9017.000000
unique,35,808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,UTTAR PRADESH,TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,878,408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2006.629034,89.28535,78.069646,9.895531,53.041366,0.005767,53.035599,79.152046,58.535433,20.616613,13.177110,7.084618,55.066430,247.829433,776.428968,281.772208,494.656759,171.881335,40.816458,170.255517,5.926140,25.219918,747.893091,20.228901,100.511257,27.515582,194.122435,0.197849,222.216702,2174.299434,5310.115116
std,NaN,NaN,3.463623,327.27503,303.446020,59.521657,190.741450,0.115223,190.725474,317.630964,246.937464,88.586415,56.778798,42.350314,220.576876,941.233426,2935.008640,1164.677928,1895.366707,685.061783,172.042434,743.536365,25.985903,98.880282,3024.106467,96.970466,394.059436,167.237522,831.986594,2.415039,936.002540,7988.438462,18524.381119
min,NaN,NaN,2001.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,2004.000000,18.00000,10.000000,0.000000,8.000000,0.000000,8.000000,10.000000,6.000000,1.000000,1.000000,0.000000,6.000000,31.000000,88.000000,12.000000,64.000000,11.000000,4.000000,13.000000,0.000000,2.000000,43.000000,1.000000,10.000000,0.000000,11.000000,0.000000,5.000000,265.000000,853.000000
50%,NaN,NaN,2007.000000,38.00000,28.000000,2.000000,20.000000,0.000000,20.000000,25.000000,18.000000,5.000000,3.000000,0.000000,17.000000,83.000000,217.000000,48.000000,152.000000,46.000000,11.000000,37.000000,1.000000,8.000000,199.000000,5.000000,31.000000,2.000000,47.000000,0.000000,68.000000,745.000000,2096.000000
75%,NaN,NaN,2010.000000,66.00000,56.000000,6.000000,41.000000,0.000000,41.000000,56.000000,42.000000,13.000000,9.000000,2.000000,37.000000,177.000000,466.000000,140.000000,313.000000,125.000000,28.000000,104.000000,4.000000,20.000000,529.000000,16.000000,76.000000,13.000000,135.000000,0.000000,177.000000,1608.000000,3972.000000
max,NaN,NaN,2012.000000,7601.00000,7964.000000,1616.000000,3425.000000,5.000000,3425.000000,8878.000000,7910.000000,2416.000000,1319.000000,1263.000000,6949.000000,16617.000000,53449.000000,22773.000000,35960.000000,11214.000000,4296.000000,19646.000000,599.000000,2830.000000,56768.000000,2322.000000,7118.000000,4970.000000,19865.000000,83.000000,16076.000000,124176.000000,220335.000000

In [17]:
df.isnull().sum()

STATE/UT                                       0
DISTRICT                                       0
YEAR                                           0
MURDER                                         0
ATTEMPT TO MURDER                              0
                                              ..
CRUELTY BY HUSBAND OR HIS RELATIVES            0
IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES    0
CAUSING DEATH BY NEGLIGENCE                    0
OTHER IPC CRIMES                               0
TOTAL IPC CRIMES                               0
Length: 33, dtype: int64

In [16]:
missing = df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [18]:
df.duplicated().sum()

np.int64(0)

### Display States

In [20]:
df["STATE/UT"].nunique()

35

In [21]:
sorted(df["STATE/UT"].unique())

['A & N ISLANDS',
 'ANDHRA PRADESH',
 'ARUNACHAL PRADESH',
 'ASSAM',
 'BIHAR',
 'CHANDIGARH',
 'CHHATTISGARH',
 'D & N HAVELI',
 'DAMAN & DIU',
 'DELHI UT',
 'GOA',
 'GUJARAT',
 'HARYANA',
 'HIMACHAL PRADESH',
 'JAMMU & KASHMIR',
 'JHARKHAND',
 'KARNATAKA',
 'KERALA',
 'LAKSHADWEEP',
 'MADHYA PRADESH',
 'MAHARASHTRA',
 'MANIPUR',
 'MEGHALAYA',
 'MIZORAM',
 'NAGALAND',
 'ODISHA',
 'PUDUCHERRY',
 'PUNJAB',
 'RAJASTHAN',
 'SIKKIM',
 'TAMIL NADU',
 'TRIPURA',
 'UTTAR PRADESH',
 'UTTARAKHAND',
 'WEST BENGAL']

### Display District

In [22]:
df["DISTRICT"].nunique()

808

In [39]:
dist=pd.DataFrame(sorted(df["DISTRICT"].unique()),columns=['District'])

dist.head()

            District
0  24 PARGANAS NORTH
1  24 PARGANAS SOUTH
2    A and N ISLANDS
3           ADILABAD
4               AGRA

In [24]:
df.dtypes

STATE/UT                                       object
DISTRICT                                       object
YEAR                                            int64
MURDER                                          int64
ATTEMPT TO MURDER                               int64
                                                ...
CRUELTY BY HUSBAND OR HIS RELATIVES             int64
IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES     int64
CAUSING DEATH BY NEGLIGENCE                     int64
OTHER IPC CRIMES                                int64
TOTAL IPC CRIMES                                int64
Length: 33, dtype: object

### Initial Observations

- The dataset contains district-wise IPC crime records from 2001 to 2012.
- Each record represents crime statistics for a district in a specific year.
- Multiple IPC crime categories are available.
- Numeric variables mainly represent reported crime counts.
- Categorical variables include State/UT and District.
- No Missing Values and duplicates Values.
- The DISTRICT column contains summary records such as 'TOTAL'.
  - These rows do not represent actual districts but state-level aggregated values.
  - These records will be handled during the data cleaning phase to avoid duplication and incorrect district-level analysis.

### Saving files Backup Before Cleaning

In [41]:
df.to_csv("crime_raw_backup1.csv", index=False)